version: '3.8'
services:

  myjenkins:
    build:
      context: .
      dockerfile: jenkins/dockerfile
    ports: 
      - 5050:8080
    networks:
      - abc


  qaserver:
    build:
      context: .
      dockerfile: tomee/dockerfile
    ports:
      - 6060:8080
    networks:
      - xyz

  prodserver:
    build:
      context: .
      dockerfile: tomee/dockerfile
    ports:
      - 7070:8080
    networks:
      - xyz

networks:
  abc: {}
  xyz: {}

...
